stages:
  - lint
  - test

python-lint:
  stage: lint
  image:
    name: "cytopia/pylint:latest"
    entrypoint: [""]
  script:
    - python3 -m pip install -r requirements.txt 
    - pylint main.py

test:
  stage: test
  image:
    name: "debian:bullseye-slim"
  script:
    - apt-get update
    - apt-get install -y python3 python3-pip
    - pip install -r requirements.txt 
    - python3 main.py --config ${pipeline_config}
